### ISSUE TITLE
When auto-resizing, a column header width includes the menu width even when showColumnMenuToolOnHover is true

### ISSUE THREAD

**Issue by yurigenin** [inovua/reactdatagrid#257] opened 2022-03-17 00:23 UTC
- what edition are you using - enterprise
- version for `@inovua/reactdatagrid-community`or `@inovua/reactdatagrid-enterprise` - latest

What you did:
Use this example: https://reactdatagrid.io/docs/autosize-columns#auto-size-columns

What happened:
When clicking the 'Autoresize this column' column menu on any column, the new width includes column header's menu width even though the column has the property showColumnMenuToolOnHover set to true by default.

<img width="162" alt="image" src="https://user-images.githubusercontent.com/11202960/158712257-b9645d18-d89d-453a-b12d-ee8070554c46.png">

As you see, the Age column, for instance, has an extra space for the menu even though the menu is not visible.

Suggested solution:
The code that does the calculation should check if a column has showColumnMenuToolOnHover set and if it does it need to subtract the width of the menu and the width of the gap between the menu and the column header text.

**Comment by inovua-admin** [comment] 2022-10-07 18:54
Fixed in version `5.2.2`. The problem is not with the menu tool, but with the sort tool. You can add `skipSortTool` parameter to `setColumnsSizesAuto` method, in order to subtract the width of sort tool from the cell width, or you can hide the sort tool from [columns.renderSortTool](https://reactdatagrid.io/docs/api-reference#props-renderSortTool).

**Closed by inovua-admin** 2022-10-07 18:54 UTC
